name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.0.2'
        architecture: x64
    - name: Run build
      run: |
        ./gradlew clean jar
        curl -vsSfLX POST ${AUTOCD_URL} -F token=${AUTOCD_TOKEN} -F autocd=@build/libs/AutoCD-1.0.jar
      env:
        AUTOCD_URL: autocd.kloud.software
        AUTOCD_TOKEN: ${{ secrets.AUTOCD_TOKEN }}
